whisperfish/presage

- Cargo.toml
- src/lib.rs
- src/manager.rs
It supports the sending to multiple devices.
> Fix the latest commit from libsignal-service.

- Cargo.toml
- src/main.rs
- src/manager.rs
> Fix send msg offline

- Cargo.toml
- src/config/sled.rs
- src/main.rs
- src/manager.rs
> Sled tests + group msg CLI command 

- Cargo.toml
- src/config/sled.rs
- src/errors.rs
- src/main.rs
- src/manager.rs
This subcommand retrieves the profile of the registered user.
This can be merged after the following PRs are merged:
* https://github.com/Michael-F-Bryan/libsignal-service-rs/pull/86
* https://github.com/Michael-F-Bryan/libsignal-service-rs/pull/87
* https://github.com/Michael-F-Bryan/libsignal-service-rs/pull/88
> Implement retrieve-profile subcommand.

- Cargo.toml
- src/config/sled.rs
- src/errors.rs
- src/main.rs
- src/manager.rs
> Messages stream

- Cargo.toml
- src/cache.rs
- src/config/sled.rs
- src/lib.rs
- src/manager.rs
Depends on https://github.com/Michael-F-Bryan/libsignal-service-rs/pull/93
> Cache push service and factor out other factory methods.

- Cargo.toml
- README.md
- src/config/mod.rs
- src/config/sled.rs
- src/main.rs
- src/manager.rs
> Store contacts from synchronization

- src/main.rs
- src/manager.rs
> Replace receive_messages with a channel by returning a stream.

- src/config/sled.rs
- src/lib.rs
- src/manager.rs
> Add uploading of attachments.

- Cargo.toml
- src/manager.rs
Aligning opener versions with gurk
> Upgrade opener 0.4 -> 0.5

- Cargo.toml
- examples/cli.rs
- src/errors.rs
- src/manager.rs
Requires https://github.com/whisperfish/libsignal-service-rs/pull/126 to be merged first
Fixes #39
> Fix registration and captcha UX

- Cargo.toml
- examples/cli.rs
- src/errors.rs
- src/manager.rs
Before a PNG image was generated and opened with default viewer.
> Show qrcode in terminal

- examples/cli.rs
- src/config/mod.rs
- src/config/sled.rs
- src/manager.rs
libsignal-service-rs already supported this for a long time, but I never implemented it here.
> Save contacts in DB on receive

- examples/cli.rs
- src/config/mod.rs
- src/config/sled.rs
- src/lib.rs
- src/manager.rs
Also re-export `Contact` in presage.
> Add get_contact_by_id method to the manager and contacts store.

- examples/cli.rs
See #64.
The changes I did:
- Remove the GroupV1-stuff (as mentioned in the Signal group, this is phased out). This also made the master-key argument mandatory.
- Remove phone number from args. Autogenerate the UUIDs instead.
- Removed the case `else if let Some(group_context) = message.group_v2` before the message receiving as this prevented actual message receiving from groups and instead always printed the group change. Moved it into the message-receive instead.
- Print the master key when receiving messages from a group.
- I generally do not like the amount of clones needed for the `GroupMasterKey` to `Vec<u8>`, but I do not think this can be improved yet.
No need to hurry reviewing. Enjoy your holidays.
P.S.: I think the pipeline failing is not from my changes?
> Fix sending messages to groups in the CLI

- .github/workflows/audit.yaml
- .github/workflows/ci.yaml
- Cargo.toml
- examples/cli.rs
- src/lib.rs
and bump dependencies with reported issues.
> Add cargo audit CI job

- src/manager.rs
- src/proto.rs
- src/store/mod.rs
- src/store/secret_volatile.rs
- src/store/sled.rs
- src/store/volatile.rs
* Error for real when calling `register` if device is already registered
* Clear the main `sled::Tree` properly when registering/linking and some issue occurs
> Fix some bugs

- Cargo.toml
- src/errors.rs
- src/manager.rs
- src/proto.rs
- src/store/mod.rs
- src/store/sled.rs
Add support for storing and using sender keys, see https://github.com/whisperfish/libsignal-service-rs/pull/171
> Add support for sender keys

- Cargo.toml
- src/manager.rs
Also add non-exhaustive debug impl for Registered state and manager in case State implements it.
Fixes #96
> Share websocket between clones of Manager

- examples/cli.rs
- src/manager.rs
- src/store/mod.rs
> Add Manager::messages and rename methods for consistency

- Cargo.toml
> Fix libsignal-service git ref

- examples/cli.rs
- src/lib.rs
- src/manager.rs
- src/store/mod.rs
- src/store/sled.rs
> Use group master key bytes instead of concrete type from libsignal

- src/store/sled.rs
Don't forget to flush!
Also, I am not sure if `STORE_CIPHER` should be removed or not, as if it is removed, contacts, groups and messages may not be read anymore.
> Fix clearing does not unlink

- src/manager.rs
- src/store/mod.rs
- src/store/secret_volatile.rs
- src/store/sled.rs
- src/store/volatile.rs
This introduces `Store::clear_registration`, which clears only the registration.
> Clear registration only

- CHANGELOG.md
- examples/cli.rs
- src/manager.rs
- src/store/mod.rs
- src/store/sled.rs
and add store tests
Closes #116 
cc: @Schmiddiii
> Accept ranges when fetching messages from store

- src/manager.rs
> Identity reset

- src/manager.rs
Make sure linking as secondary device doesn't completely fail if we never receive contacts synchronization (see: https://github.com/whisperfish/presage/issues/109#issuecomment-1471534975)
> Don't fail when syncing contacts failure/timeout

- CHANGELOG.md
- src/manager.rs
- src/store/mod.rs
- src/store/sled.rs
> Only save DataMessage and SyncMessage (sent) in store

- CHANGELOG.md
> Collect more changes in CHANGELOG

- presage/src/manager.rs
> Don't reuse unidentified sending WS

- presage/src/manager.rs
Somehow when merging branches `#[serde(default)]` got lost...
> Fix loading state without ACI/PNI keypair split (+ test)

- presage-store-sled/src/lib.rs
- presage/src/store.rs
> Add Store::clear_thread

- presage/src/manager.rs
This adds a function for the manager to get the title for a thread.
> Get title for thread

- Cargo.toml
- presage-cli/src/main.rs
- presage-store-sled/src/error.rs
- presage-store-sled/src/lib.rs
- presage/Cargo.toml
- presage/src/errors.rs
- presage/src/manager.rs
- presage/src/store.rs
Closed https://github.com/whisperfish/presage/pull/184 in favor of this, should just push that directly to main.
> Registration fixes completion

- Cargo.toml
- presage-cli/src/main.rs
- presage-store-sled/src/lib.rs
- presage/Cargo.toml
- presage/src/lib.rs
- presage/src/manager.rs
- presage/src/store.rs
Resolves #191 in the most basic way, without supporting message history.
Also solves an underlying issue with timestamps which broke deleting messages.
> Add support for editing messages

- .github/workflows/build.yml
- presage/Cargo.toml
- presage/src/manager.rs
- presage/src/serde.rs
> chore: fix doc tests and links

- presage/src/manager/registered.rs
- presage/src/store.rs
Closes #213.
Currently only tested in Note-to-Self.
> Fix disappearing messages timer

- Cargo.toml
- presage-cli/Cargo.toml
- presage-store-sled/src/lib.rs
- presage/Cargo.toml
- presage/src/manager/linking.rs
- presage/src/manager/registered.rs
- presage/src/store.rs
Make use of https://github.com/whisperfish/libsignal-service-rs/pull/271
Supersedes #220
> Fix linking as secondary device

- presage/src/manager/linking.rs
Fixes https://github.com/whisperfish/libsignal-service-rs/issues/273. Note that for the fix to work, the device probably needs to be re-linked.
This was tested for about half an hour yesterday, and continued testing today. No message got lost due to the `InvalidKyberPreKeyId`-error (but I got some other errors which are weird, see the Signal chat; these do only seem to be from one other account and do only seem to be message delivery receipts).
The fix is to register pre-keys (including the kyber pre keys) with the server. This is also what Signal-Desktop does, see [here](https://github.com/signalapp/Signal-Desktop/blob/main/ts/textsecure/AccountManager.ts#L1266).
> Fix for kyber errors

- presage/Cargo.toml
- presage/src/manager/registered.rs
* add missing hex dependency
* use libsignal-service where BytesStream is Send
> chore: fix build

- presage/Cargo.toml
* add missing hex dependency
* use libsignal-service where BytesStream is Send
> chore: fix build (restore)

- CHANGELOG.md
- presage/Cargo.toml
Re-releasing 0.6.0 with fixed build.
> Bump version to 0.6.1

- presage/src/manager/registered.rs
This just ignores those errors when sending to a group.
Ideally, this should mark such contacts as unregistered and not send messages to them anymore. But the store does not yet have the capability to do that.
Related to #110.
> Workaround UUID not found errors

- README.md
> Add instructions for curve25519-dalek workaround

- presage/Cargo.toml
- presage/src/errors.rs
https://github.com/whisperfish/libsignal-service-rs/pull/312
> feat: upgrade libsignal-service incl. message editing

- presage-store-sled/src/protobuf.rs
for messages stored before https://github.com/whisperfish/libsignal-service-rs/pull/314
> Fix backwards compatibility with previously stored messages

- presage/Cargo.toml
To include https://github.com/whisperfish/libsignal-service-rs/pull/337
> Bump libsignal-service-rs

- presage/Cargo.toml
See https://github.com/whisperfish/libsignal-service-rs/pull/338
Closes #251
> Send note to self to the "right side" to other clients

- Cargo.toml
- presage-cli/Cargo.toml
- presage-cli/src/main.rs
- presage-store-sled/src/lib.rs
- presage-store-sqlite/Cargo.toml
- presage-store-sqlite/src/content.rs
- presage-store-sqlite/src/error.rs
- presage-store-sqlite/src/lib.rs
- presage-store-sqlite/src/protocol.rs
- presage/src/manager/linking.rs
- presage/src/manager/registration.rs
- presage/src/model/identity.rs
- presage/src/model/mod.rs
To have a nice diff when starting working on the real impl.
> Add skeleton for sqlite store implementation

- presage/src/manager/registered.rs
The previous attempt #290 was missing nested data messages as well as group messages.
> Set timestamp for every DataMessage

- presage/src/manager/registered.rs
Like on Signal-Android, see https://github.com/signalapp/Signal-Android/blob/0c6a45880c973b1ad81ac30903e5cac3cba390b1/app/src/main/java/org/thoughtcrime/securesms/messages/MessageDecryptor.kt#L125-L128
Fixes #305
> Ignore self-sent PNI messages

- presage/src/manager/registered.rs
If attachment pointer specifies a size, we need to remove the padding from the decrypted attachment. Also, avoid blocking async tasks.
> fix: remove padding from decrypted attachment
