- Cargo.toml
- src/main.rs
Actix beta releases are not compatible atm and fail to compile.
Also upgrade to the latest libsignal-service version.
> Fix compilation by pinning actix beta versions.

- src/lib.rs
Exposes the State enum in prelude so that the ConfigStore state can be properly matched against
> Expose State in prelude

- src/errors.rs
- src/manager.rs
Also expose `is_registered` method and remove optional credentials
state.
> Fix panic when receiving messages if the device is not registered.

- src/lib.rs
- src/main.rs
- src/manager.rs
The ConfigStore trait already requires all other trais being
implmented, so there is no need to store them.
This also makes the random generator parameter default.
> Use a single ConfigStore param in Manager.

- Cargo.toml
- src/config/mod.rs
- src/config/sled.rs
- src/errors.rs
- src/lib.rs
- src/main.rs
- src/manager.rs
Depends on https://github.com/Michael-F-Bryan/libsignal-service-rs/pull/83
> Use the Rust version of libsignal-protocol

- README.md
- src/errors.rs
- src/manager.rs
The metadata is already part of the AttachmentPointer protobuf message.
This function downloads the attachment from the CDN and then decrypts it.
> Expose downloading + decrypting attachment

- src/lib.rs
This commit exposes the ConfigStore trait publicly so that state can be queried
> Expose ConfigStore trait

- src/config/sled.rs
Currently, presage does not build due to the recent changes to `libsignal-service`. This quick change allows the crate to compile.
Surprisingly, out of the five different instances of `#[async_trait(?Send)]`, this one is the only one that can actually be changed to `#[async_trait]`. All the others will fail to compile due to the `_ctx` pointer in the upstream `libsignal-client`. But for `SessionStoreExt` specifically, the change compiles out of the box. This works out quite nicely, as we can keep things building even while we are waiting on signalapp/libsignal-client#297.
> Use Send async_trait for SessionStoreExt

- src/manager.rs
When registering a new device and calling `request_contact_sync`, the `send_message` function is called with the user phone number as first argument.
However, this can't work since the store saves user information by uuid and not by phone number. If the keys aren't found in the store, then no encrypted message is given to the server and then, the request fails (http 404 error). It isn't critical but the register process partially fails.
I think that the `let phone_number = ...`  line and the last line should be replaced by something about uuid so it is possible to find the corresponding keys as proposed in this pull request.
Fixes #35
> First contact sync with UID

- src/lib.rs
- src/manager.rs
Since this commit [Rewrite Manager to use type states](https://github.com/whisperfish/presage/commit/55772b71b10c8b8dfb8f8e9e92f5339c4d4d7a57) , States are not exported anymore (usefull to be able to manipulate a manager outside of presage), and uuid() method was removed
thank you
> Reexport States and uuid() function

- examples/cli.rs
- src/config/mod.rs
- src/config/sled.rs
- src/config/volatile.rs
- src/lib.rs
This can be useful when you don't want any keys or secret data persisted anywhere, the downside being that all data is lost when you drop the instance of the config store (like when the process exits/dies).
Note: the `VolatileConfigStore` doesn't store contacts.
This is mostly tailored to the use-case of @Philipp-Sc described in #50.
> Add a volatile store implementation

- Cargo.toml
- src/errors.rs
- src/manager.rs
Currently linking a device prints the corresponding QR code into the terminal. This is not really usefull for e.g. graphical clients. This PR makes the linking more generic by providing a callback function that is called with the URL to link with.
This has one disadvantage that error handling is a little bit worse as one cannot exactly identify the type of the error, I therefore just created a unparametrized `LinkError` that is given if the callback returns an error.
I also made the `qr2term` package a optional but default feature so that it can be disabled for graphical applications.
> More generic way of linking device

- src/lib.rs
- src/manager.rs
Currently, implementing a custom `ConfigStore` outside of `presage` is not possible, mainly as `ContactsStore` and `StateStore` are not publicly accessible. Futhermore, some data in `Registered` needs to be public to be stored in the `StateStore`. This PR basically just makes all of these needed things public.
I also thought about maybe hiding the exports behind a feature, as most people will probably not need to create their own `ConfigStore`, but having the option is still needed as sometimes the built-in stores may not suffice.
Also note that the CI is currently failing, I did not change anything there so it will probably also fail in this PR.
> Export things needed to create custom ConfigStore

- Cargo.toml
- examples/cli.rs
- src/config/mod.rs
- src/config/secret_volatile.rs
- src/lib.rs
This adds `SecretVolatileConfigStore` using utilities provided by [libsodium](https://download.libsodium.org/doc/memory_management) via the [secrets](https://github.com/stouset/secrets) crate.
To my understanding this only protects the data copied into the store. Any values moving around via `manager.rs` are not protected. 
1) @gferon Does the `manager` contain data that should also be hidden? E.g State: `Registered`?
2) To reduce the exposure further this would require a more thigh integration. 
I.e making sure the data that is passed to the `SecretVolatileConfigStore` is mutable, see `SecretBox` implementation:
```    
///
/// Existing data can be moved into a [`SecretBox`]. When doing so, we
/// make a best-effort attempt to zero out the data in the original
/// location. Any prior …
```
> SecretVolatileConfigStore added

- Cargo.toml
- build.rs
- examples/cli.rs
- src/config/mod.rs
- src/config/secret_volatile.rs
- src/config/sled.rs
- src/errors.rs
- src/lib.rs
- src/manager.rs
- src/proto.rs
- src/protobuf/InternalSerialization.proto
This is a initial draft for message storage. The trait behind message storage is `MessageStore`, which is currently only has very basic functionality, e.g. storing and retrieving messages by sender and timestamp, listing all messages. This should definitely be expanded in the future with e.g. associating messages with channels/groups, listing messages from channels/groups. I don't think searching would be easily possible as sled (the main current implementation) is basically just a key-value store and not intended to be searchable (as far as I see).
The message serialization/deserialization is done using protobuf. I think the additional work done here (mainly the `InternalSerialization.proto` with function implementations) should be upstreamed to `libsignal-service-rs`
For receiving …
> Message storage

- Cargo.toml
- README.md
- examples/cli.rs
- src/errors.rs
- src/lib.rs
- src/manager.rs
- src/proto.rs
- src/store/mod.rs
- src/store/secret_volatile.rs
- src/store/sled.rs
- src/store/volatile.rs
Implement encryption of the values stored in the `sled::Db` which is in theory the last missing feature in `presage` 🥳
This breaks again the compatibility of previous sled stores (sorry 😢) since I also took the opportunity to refactor the code and introduce this change with more removed code than added (!)
EDIT: will not merge this before I come up with some sort of schema migration system (which shouldn't be too hard, but will take a bit of extra time)
> Implement local encryption

- examples/cli.rs
the retrieve profile asks for a profile key even when presage has that information already. This patch looks in the registered tree for the profile key.
> If no profile_key is provided try to get it from the registered contacts

- Cargo.toml
- examples/cli.rs
- src/errors.rs
- src/manager.rs
- src/store/sled.rs
This brings a newer version of `libsignal-service-rs` with relevant changes.
Contacts sync will now wait until it is done, like Signal Desktop does.
> Use SignalWebSocket

- src/store/sled.rs
Currently, message timestamps are encrypted when storing. This does not work when retrieving messages before a timestamp (and I think currently does not work when getting/deleting messages in general). This PR fixes this by just removing the encryption.
Before this PR should actually be merged, it should maybe be discussed if removing the encryption is actually a good thing to do, but as far as I see it is the only thing possible except for every time we look for messages of a thread, decrypt all message keys and manually sort and iterate them.
> Fix storing messages

- examples/cli.rs
- src/store/sled.rs
The range used for `sled` was inverted.
#116
> Fix retrieving message from a timestamp

- src/store/mod.rs
- src/store/secret_volatile.rs
- src/store/sled.rs
- src/store/volatile.rs
This (ab)uses the fact that all thread-trees start with `thread`. I don't know if that should be seen as an interpretation detail of `messages_thread_tree_name` and should therefore be clasified as a workaround. Another option may be to instead query possible `Thread` first and then calculate the thread name, but this would tightly couple the three Store-traits and one would be careful in which order to delete the data.
> Clear messages

- src/manager.rs
This previously returned `MessagePipeNotStarted` as the message pipe was not yet started when sending the request for contact syncing. This behavior was introduced in #106.
> Fix contacts syncing after linking

- src/store/sled.rs
Previously, the registration was not encrypted. As this contains (as far as I have seen) keys of the device, it could be used to link an unauthorized device with the stored data.
This commit encrypts the data. This will break previously used instances of the store and may therefore require a migration, which I have not yet investigated.
> Encrypt registration

- Cargo.toml
- examples/cli.rs
- src/manager.rs
- src/store/mod.rs
- src/store/sled.rs
~~Dependent on upstream PR <https://github.com/whisperfish/libsignal-service-rs/pull/207>. Therefore, my fork is currently uses but should be changed to upstream as soon as merged there.~~
This is very similar to <https://github.com/whisperfish/presage/pull/130> and provides pretty much the same functionality for profiles.
Maybe after both are merged, a function `clear_cache` would be useful for the stores.
> Cache for profile

- src/manager.rs
Currently, when sendinging a message to a group, this message will be sent both as a data message to linked devices and as a sync message. As discussed in the whisperfish-chat, the recipients-list should not contain the own UUID. As also discussed, this breaks sending to groups with only the sender and no other persons, this has to be fixed upstream.
> Fix duplicate message to group

- CHANGELOG.md
- Cargo.toml
- examples/cli.rs
- src/manager.rs
- src/store/mod.rs
- src/store/sled.rs
This does two things when receiving a message deletion request:
- Nullify the sender UUID
- Replace the `DataMessage` previously stored by a `NullMessage`
> Handle message deletion requests

- presage/src/manager.rs
I was informed by @rubdos that the identity reset I implemented was actually a session reset.
> Rename identity to session reset

- CHANGELOG.md
- presage-cli/src/main.rs
- presage-store-sled/build.rs
- presage-store-sled/src/lib.rs
- presage/Cargo.toml
- presage/src/errors.rs
- presage/src/manager.rs
- presage/src/store.rs
> Send messages as unidentified sender

- CHANGELOG.md
- presage-store-sled/src/lib.rs
Since we receive events asynchronously in the websocket, and spawn decryption, it is very important that we guard concurrent decryption as it can perform write operations on the store.
This is probably the reason of session storage corruption like reported in #158.
> Re-introduce RwLock around sled::Db

- Cargo.toml
- presage-cli/src/main.rs
- presage-store-sled/src/lib.rs
- presage/Cargo.toml
- presage/src/manager.rs
- presage/src/store.rs
- Introduce updating account attributes to set support for PNI (phone number identity)
- Retrive the PNI UUID and store it in our local state
- Fix group metadata fetching and verification, which uses the PNI UUID
> Fix fetching groups and receive PNI identity

- presage/src/manager.rs
I noticed that sometimes `receive_messages()` will terminate instead of blocking for new messages. When internal messages aren't desired, the closure returns `None`. I believe this causes `futures::stream::unfold()` to return `Poll::Ready(None)` which will close the stream. I don't think that's what we want.
I suggest we just continue looping when skipping internal messages instead of returning None.
> manager: continue when skipping internal msgs

- presage/Cargo.toml
- presage/src/manager.rs
- presage/src/store.rs
This sets the expire timer of a message such that the current expiration timer of a conversation stays the same (except in cases where it was explicitly set to another value).
It may be a little counterproductive when sending a message to (e.g.) a contact to query the timer for the thread which unwraps it back to querying the contact, but this method may potentially also be used to display the expiration timer.
Note that due to #171, I would guess that the expiration timer always stays the same for contacts directly after linking, e.g. changing it on an official client and then sending a message from presage, presage will set the expiration timer back to before the change.
This fixes #93.
P.S.: The panic when the group bytes are not 32 bytes in length is maybe not that good. Is there a …
> Set the expire timer

- presage-store-sled/src/lib.rs
- presage/Cargo.toml
- presage/src/lib.rs
- presage/src/manager.rs
- presage/src/store.rs
* This meant a much higher CPU usage than expected when loading groups often as we would decrypt groups whenever they're accessed.
* Since the store can be optionally encrypted with a passphrase, this would also means the data was encrypted twice.
cc: @nanu-c 
Closes #122
> Store decrypted groups

- presage-cli/src/main.rs
The clap arg-group needs the field name of the struct
Otherwise you get this:
```bash
thread 'main' panicked at 'Command list-messages: Argument group 'list-messages' contains non-existent argument 'recipient-uuid'', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.3.19/src/builder/debug_asserts.rs:292:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After:
```bash
error: the following required arguments were not provided:
<--recipient-uuid <RECIPIENT_UUID>|--group-master-key <GROUP_MASTER_KEY>>
Usage: presage-cli list-messages <--recipient-uuid <RECIPIENT_UUID>|--group-master-key <GROUP_MASTER_KEY>>
For more information, try '--help'.
```
Which is expected
> Fix arg group syntax

- .github/workflows/build.yml
- Cargo.toml
- presage-store-cipher/Cargo.toml
- presage-store-cipher/src/lib.rs
- presage-store-sled/Cargo.toml
- presage-store-sled/src/error.rs
- presage-store-sled/src/lib.rs
Even though, the implementation of `presage_store_cipher::StoreCipher` is almost verbatim along the lines in `matrix-sdk-store-encryption`, our custom implementation allows us to decouple from dependencies of matrix and their release process.
Also fix `encryption` feature flags: now it is possible to use presage-store-sled without encryption.
> Replace matrix-sdk-store-encryption by our own store cipher

- presage/src/manager.rs
In the presage-store-sled implementation, `load_state` always returns `Ok(_)` (except for errors). Therefore, the registration condition that determines if the store was already registered, `!force && config_store.load_state.is_ok()` is always `true` when `force == false`. Instead, one should use `config_store.is_registered()` to figure out if the store is already registered.
> Fix registration without force

- presage/Cargo.toml
- presage/src/lib.rs
- presage/src/manager.rs
Add a new method `Manager::receive_messages_with_mode` allowing to
configure how to handle specific sentinel messages. It is supported to
stop the stream after the initial sync (empty Signal message queue) or
after contact sync.
> feat: Add receiving mode to the message stream

- .github/workflows/build.yml
- presage-cli/src/main.rs
- presage-store-sled/src/error.rs
- presage-store-sled/src/lib.rs
- presage-store-sled/src/protobuf.rs
- presage/src/errors.rs
- presage/src/lib.rs
- presage/src/manager.rs
- presage/src/manager/confirmation.rs
- presage/src/manager/linking.rs
- presage/src/manager/mod.rs
- presage/src/manager/registered.rs
- presage/src/manager/registration.rs
- presage/src/store.rs
There are several goals of this refactoring:
1. Importing of types should be obvious and unique. We try not to
re-export types (with the exception of the `Manager` and `protos`).
2. The Store trait is split and is not an overarching trait anymore.
Instead it is combined from several smaller traits, each responsible
for a non-overlapping feature.
3. All public modules and types are documented (in presage).
4. `Manager` file is split in a file per type state.
Since public exports are removed and reordered, this is a breaking 
change.
TODO:
> Split into multiple module, document all structs and general cleanup

- presage/src/cache.rs
- presage/src/manager/confirmation.rs
- presage/src/manager/registered.rs
Cache both identified and unidentified `PushService` as well as the websockets.
> fix: reuse websockets

- presage/src/manager/linking.rs
- presage/src/manager/registered.rs
Contacts syncing is still not working (#194) at linking time (anymore) so I would rather disable it while we try and fix all issues that could make it work again.
> hotfix: Disable initial contacts sync for the time being

- presage-cli/src/main.rs
- presage-store-sled/src/lib.rs
- presage/src/manager/linking.rs
- presage/src/manager/registration.rs
- presage/src/store.rs
I never realized this was wrong, and I guess I kept re-linking as part of my tests, but there was no way for `presage` since a _very long_ time (maybe even forever) to receive messages from a contact that changed their identity (which happens when you change your phone, for example).
This PR fixes this and follows the default behavior of official Signal clients.
A `SyncMessage` is inserted in the 1-1 thread with the contact whose identity changed, which a client can interpret to display the "Your safety number with [CONTACT] has changed".
Currently, the values are used in the following way:
- `verified::State::Default` will always be saved in the timeline when the new identity is saved
- `verified::State::Unverified` will be save in the timeline when the safety number changed, letting …
> fix: trust new identities

- presage-cli/src/main.rs
- presage/Cargo.toml
- presage/src/manager/registered.rs
Also:
- Save profile keys from incoming message also from `SyncMessage`
- Remove quirks feature flag from `presage-cli`
- Remove sleep when sending messages with CLI now that the websockets are handled properly
Relates to #200
> Send profile key with messages

- presage-cli/src/main.rs
- presage-store-sled/src/lib.rs
- presage/Cargo.toml
- presage/src/manager/registered.rs
Make use of https://github.com/whisperfish/libsignal-service-rs/pull/263
- Fix contacts syncing _at least_ when the account has been working for a bit of time
- Fix CLI hanging when sending messages (both to contacts and groups)
Closes #200
> Fix some issues around SyncMessage

- presage-cli/src/main.rs
- presage-store-sled/src/lib.rs
- presage/src/manager/registered.rs
- presage/src/store.rs
Closes #98 and #171
Also fixes updating profile keys (tentatively added a few commits ealier) which was in the wrong place (silly giant `match` statements).
> Upsert a contact when seeing it for the first time

- presage-cli/src/main.rs
- presage/src/manager/registered.rs
It is actually required to wait for all messages to sync on startup (like Signal-Desktop does) _before_ letting users send messages.
The feature was there, but this change is a minor breakage of the API to make sure clients handle this correctly.
> Enforce selecting a mode when receiving messages

- presage/src/manager/registered.rs
- presage/src/store.rs
Outgoing messages in 1-to-1 chats were stored in the note-to-self chat. This was broken in 6125534. This will be fixed by this MR.
This also fixes the timestamp of identity verification messages, which are inserted into the store by presage. By convention, all timestamps used are in milliseconds, this one was in seconds. This was wrong since #206.
> Fix outgoing messages stored in wrong thread

- presage/Cargo.toml
- presage/src/manager/registered.rs
When identified or unidentified websocket is used, it is checked whether it is closed, and in that case it is reconnected. This is less powerful to auto-reconnecting websockets, because the messages stream would not be interrupted. But this is a very simple implementation which works quite well on application level.
> Reconnect websockets lazily on usage

- presage-store-sled/src/lib.rs
This caused issues for me with out-of-sync kyber and normal pre keys.
> Drop kyber pre keys on relinking

- presage/Cargo.toml
- presage/src/manager/registered.rs
When `receive_messages` is called multiple times on the same manager, this could lead to a panic "web socket request handler not in use". This fixes this.
Requires <https://github.com/whisperfish/libsignal-service-rs/pull/274>. Also currently dependent on my fork of lss.
> Fix reuse of websocket

- presage/src/manager/registered.rs
I had the assumption that once an expire timer was set, the field would always be populated. I think now that this assumption is wrong. Therefore, one should only update the expire timer if the field is really set.
> Potential fix for expire timer turning off

- presage-store-sled/src/lib.rs
Bubble up any error when running migrations that's not `MigrationConflict`. We should only apply the migration strategy if we have any unrecoverable error (and leave the choice of what to do to the user).
Fixes https://github.com/boxdot/gurk-rs/issues/261
> fix: don't run migration conflict strategy when opening the sled store more than once

- presage-store-sled/src/lib.rs
- presage/Cargo.toml
- presage/src/errors.rs
- presage/src/lib.rs
- presage/src/manager/registered.rs
- presage/src/store.rs
A few TODOs are left which I am unsure about:
> Add functions to retrieve avatars

- presage-cli/src/main.rs
- presage/Cargo.toml
- presage/src/errors.rs
- presage/src/manager/mod.rs
- presage/src/manager/registered.rs
Currently does not work due to an issue on the secondary-side:
```
ProvisioningError(InvalidData { reason: "missing client UUID" })
```
The code was mostly copied from what Whisperfish is doing.
Depends on https://github.com/whisperfish/libsignal-service-rs/pull/250
> Link secondary devices as primary device

- presage-cli/src/main.rs
- presage-store-sled/src/lib.rs
Without this we are stuck on v4, and always run the migration step. The migration sometimes fails because the there is no properly serialized data.
Also allow to specify the database path and secret at the same time.
> fix: ignore sometimes failing migration v4 -> v5

- presage/Cargo.toml
- presage/src/manager/registered.rs
- presage/src/store.rs
See whisperfish/libsignal-service-rs#321 for more details
NB: my Rust skills compare unfavorably to those of an amoeba, and as such it is entirely possible I have done something horribly wrong.
> Add support for versioned expire timers

- presage/src/manager/registered.rs
This was modified in f93f2dee5b9f0ca3b30b545143194431d9136549 and the bug slipped in.
> Fix wrong expiration comparison for sender certificates

- presage-cli/src/main.rs
- presage-store-sled/src/content.rs
- presage-store-sled/src/protobuf.rs
- presage/Cargo.toml
- presage/src/lib.rs
- presage/src/manager/registered.rs
- presage/src/model/groups.rs
- presage/src/model/mod.rs
- presage/src/store.rs
Introduce the first few mirror structs to avoid store breakage when things change on the lss side.
> Adjust code to latest libsignal-service-rs

- presage/src/manager/registered.rs
This was missing and would create duplicate sessions.
> Use the right ServiceCipher for incoming PNI messages

- presage-cli/src/main.rs
- presage-store-sled/src/content.rs
- presage-store-sled/src/lib.rs
- presage-store-sled/src/protocol.rs
- presage/Cargo.toml
- presage/src/manager/confirmation.rs
- presage/src/manager/linking.rs
- presage/src/manager/registered.rs
- presage/src/manager/registration.rs
- presage/src/model/groups.rs
- presage/src/model/mod.rs
- presage/src/store.rs
Since everything else was already `async` it shouldn't be a massively breaking change. This is in preparation of adding other implementations of the store traits, namely `sqlx` with `sqlite`.
> [breaking] Switch Store traits to async Rust

- Cargo.toml
- presage-store-sled/src/lib.rs
Otherwise newly registered/linked stores (currently only `sled`) will go through all migrations.
> Fix default schema version

- presage-cli/src/main.rs
- presage-store-sled/src/lib.rs
- presage-store-sled/src/protobuf.rs
- presage-store-sled/src/protocol.rs
- presage-store-sqlite/src/protocol.rs
- presage/Cargo.toml
- presage/src/manager/confirmation.rs
- presage/src/manager/linking.rs
- presage/src/manager/mod.rs
- presage/src/manager/registered.rs
- presage/src/manager/registration.rs
- presage/src/model/groups.rs
- presage/src/model/mod.rs
- presage/src/store.rs
Update `libsignal-service-rs` to include recent fixes to make sure we use the same `Rng` everywhere. This is an attempt to fix an issue where sessions are reset by the official clients on the other side.
Issues that should be fixed once `gurk` starts using this:
- https://github.com/boxdot/gurk-rs/issues/281
- https://github.com/boxdot/gurk-rs/issues/234
> Bump libsignal-service with adjustments

- presage/src/manager/confirmation.rs
- presage/src/manager/linking.rs
- presage/src/manager/mod.rs
- presage/src/manager/registered.rs
- presage/src/manager/registration.rs
- presage/src/store.rs
StdRng was cloned, which created a new rng with the same state. This
means that the same random numbers were generated:
```rust
use rand::{Rng, SeedableRng};
use rand::rngs::StdRng;
let mut rng1 = StdRng::from_entropy();
let mut rng2 = rng1.clone();
assert_eq!(rng1.gen::<u32>(), rng2.gen::<u32>());
```
This commit replaces the `StdRng` with `ThreadRng` in all places where it
was used. It also does not store the rng in manager anymore.
The credits for finding this bug go to @hrdl-github
<31923882+hrdl-github@users.noreply.github.com>.
> fix: rng state reusage

- presage/src/manager/registered.rs
This imitates the behaviour of Signal-Desktop and is required to pass envelope content validation. Previous reactions would emit this field.
This is less error-prone than requiring clients to send the timestamp in data messages.
Fixes some more instances of https://github.com/boxdot/gurk-rs/issues/110 and https://github.com/boxdot/gurk-rs/issues/147.
> Set timestamp for every DataMessage

- presage/Cargo.toml
To get two important patches:
- https://github.com/whisperfish/libsignal-service-rs/pull/351 (backend refuses to establish websocket connection without this change)
- https://github.com/whisperfish/libsignal-service-rs/pull/350
> Bump libsignal-service

- presage-store-sled/src/lib.rs
- presage-store-sled/src/protobuf.rs
- presage/Cargo.toml
- presage/src/manager/registered.rs
- presage/src/store.rs
Brings resolution patches for the following security advisories:
- https://github.com/whisperfish/libsignal-service-rs/security/advisories/GHSA-hrrc-wpfw-5hj2
- https://github.com/whisperfish/libsignal-service-rs/security/advisories/GHSA-r58q-66g9-h6g8
> chore: upgrade libsignal-service

- presage/Cargo.toml
Updates `libsignal-service-rs` to include https://github.com/whisperfish/libsignal-service-rs/pull/356 from @ccstolley.
> Fix attachment uploads to CDN3

- presage/Cargo.toml
To be able to use [block_in_place](https://docs.rs/tokio/latest/tokio/task/fn.block_in_place.html).
This is unfortunately a leaky abstraction from tokio. I would however not expect any user of this library to use anything but the default tokio rt-multi-thread runtime.
Fixes standalone compilation of `presage` and docs generation in CI.
> Add tokio::rt feature flag

- presage/src/manager/registered.rs
#307 wrapped `decrypt_in_place()` in `block_in_place()`, which makes it impossible to run the manager on a single-threaded executor:
```
thread '<unnamed>' panicked at /home/kaspar/.cargo/git/checkouts/presage-ce211e77a0d9397d/0da7b57/presage/src/manager/registered.rs:1045:9:
can call blocking only when running on the multi-threaded runtime
```
I guess there was an issue with larger attachments. So this PR makes tokio spawn a thread for the decryption, if the attachment size exceeds a threshold value. I arbitrarily set that threshold to 100k.
> Offload large attachment decryption to another thread

- presage-store-sqlite/Cargo.toml
`cargo deny` of Flare CI was complaining.
As far as I see, the license is pretty much enforced either way as the sqlite store depends on presage, which is also licensed `AGPL-3.0-only`. But I'm not a lawyer, so maybe in theory we could also use another license. But as all other presage crates are already licensed `AGPL-3.0-only`, this would probably not make too much sense.
One should maybe also add an `authors` field.
Ping @boxdot as he wrote most of the store.
> Add license to sqlite store crate

- Cargo.lock
- presage-cli/Cargo.toml
- presage-cli/src/main.rs
- presage-store-sled/Cargo.toml
- presage-store-sled/src/content.rs
- presage-store-sled/src/lib.rs
- presage-store-sled/src/protocol.rs
- presage-store-sqlite/Cargo.toml
- presage/Cargo.toml
The `sled` store is deprecated (mostly because the crate has been inactive for too long now, and makes our life harder since it's not easy to migrate the schema). The recommended store is now `presage-store-sqlite`.
Closes https://github.com/whisperfish/presage/issues/330
> Deprecate sled store
